version: '3.4'

services:

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "ultrasecreto"
      MYSQL_DATABASE: "mutant_test_db"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "supersecreto"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306

  mutanttest.api:
    image: ${DOCKER_REGISTRY-}mutanttestapi
    build:
      context: .
      dockerfile: MutantTest.API/Dockerfile
    ports:
      - 80:80
    depends_on:
      - database
