version: '3.4'

services:

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "ultrasecreto"
      MYSQL_DATABASE: "mutant_test_db"          

  mutanttest.api:
    image: ${DOCKER_REGISTRY-}mutanttestapi
    build:
      context: .
      dockerfile: MutantTest.API/Dockerfile    
    volumes:
      - ./Logs:/app/Logs
    ports:
      - 80:80
    depends_on:
      - database
